version: '3.6'

services:
    bootstrap:
        image: devp2p
        entrypoint: "./devp2p --verbosity 5 discv5 listen --bootnodes enode://582299339f1800f3ff3238ca8772b85543b5f5d4c1fab8d0a00c274a7bcf2cccb02ea72d250ee22b912d006b5a170c15c648cc2476d738baabb8519da7a7bd70@go-ethereum_bootstrap_1:0?discport=32000 --nodekey 7fbc0a865aad6ff63baf1d16e62c07e6cc7427d1f1fc99081af758d6aa27175b --addr go-ethereum_bootstrap_1:32000 --rpc go-ethereum_bootstrap_1:22000" 
        volumes:
          - ./discv5-test:/go-ethereum/discv5-test 
    devp2p:
        image: devp2p
        entrypoint: sh start_node.sh
        volumes:
          - ./discv5-test:/go-ethereum/discv5-test        
