// Code generated by "stringer -type RegAttemptState"; DO NOT EDIT.

package topicindex

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Standby-0]
	_ = x[Waiting-1]
	_ = x[Registered-2]
}

const _RegAttemptState_name = "StandbyWaitingRegistered"

var _RegAttemptState_index = [...]uint8{0, 7, 14, 24}

func (i RegAttemptState) String() string {
	if i < 0 || i >= RegAttemptState(len(_RegAttemptState_index)-1) {
		return "RegAttemptState(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _RegAttemptState_name[_RegAttemptState_index[i]:_RegAttemptState_index[i+1]]
}
